In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [3]:
def stand_manual(data):
    n_mean = np.mean(data)
    n_std = np.std(data)
    l_data = len(data)

    for i in range (0, l_data):
        data[i] =(data[i] - n_mean) / n_std
    
    return data

In [4]:
nilai = [10,11,12,14,15,18,20]
nilai_std = stand_manual(nilai)
nilai_std

[-1.2565617248750867,
 -0.9633639890708998,
 -0.670166253266713,
 -0.08377078165833932,
 0.2094269541458475,
 1.0890201615584079,
 1.6754156331667815]

In [5]:
data = ([[100, 0.001],
         [8, 0.05],
         [50, 0.05],
         [88, 0.07],
         [4, 0.1]])

scaler = StandardScaler()
scaled = scaler.fit_transform(data)
scaled

array([[ 1.26398112, -1.64763536],
       [-1.06174414, -0.13007648],
       [ 0.        , -0.13007648],
       [ 0.96062565,  0.48933531],
       [-1.16286263,  1.418453  ]])

In [6]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

poly = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['POLBAN'],
    ['POLIJE']

]

poly_enc = oe.fit_transform(poly)
poly_enc


array([[4.],
       [0.],
       [1.],
       [2.],
       [3.]])

In [8]:
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder()

poly = [
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['POLBAN'],
    ['POLIJE']

]

poly_enc = oh.fit_transform(poly)
poly_enc.toarray()




array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [9]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer()

dt = [
        {'name' : 'POLINEMA'},
        {'name' : 'PENS'},
        {'name' : 'PNJ'},
        {'name' : 'POLBAN'},
        {'name' : 'POLIJE'},

]

poly_dv = dv.fit_transform(dt)
poly_dv.toarray()


array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
#corpus/text

corpus = [
            'the house had a tiny little mouse',
            'the cat saw the mouse',
            'the mouse ran away from the house',
            'the cat finally ate the mouse',
            'the end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)


  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [15]:
vectorizer.get_feature_names()

['ate',
 'away',
 'cat',
 'end',
 'finally',
 'house',
 'little',
 'mouse',
 'ran',
 'saw',
 'story',
 'tiny']

In [13]:
response.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.4755751 , 0.58946308, 0.28088232, 0.        , 0.        ,
         0.        , 0.58946308],
        [0.        , 0.        , 0.58873218, 0.        , 0.        ,
         0.        , 0.        , 0.34771471, 0.        , 0.72971837,
         0.        , 0.        ],
        [0.        , 0.58946308, 0.        , 0.        , 0.        ,
         0.4755751 , 0.        , 0.28088232, 0.58946308, 0.        ,
         0.        , 0.        ],
        [0.58946308, 0.        , 0.4755751 , 0.        , 0.58946308,
         0.        , 0.        , 0.28088232, 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.67009179, 0.        ,
         0.        , 0.        , 0.31930233, 0.        , 0.        ,
         0.67009179, 0.        ]])